labels = sorted(['Grapefruit Pink',
'Apple Crimson Snow',
'Potato Red Washed',
'Pineapple',
'Cherry Wax Red',
'Fig',
'Peach Flat',
'Raspberry',
'Maracuja',
'Plum 2',
'Cactus fruit',
'Cherry 2',
'Mandarine',
'Grape White',
'Corn Husk',
'Grape Blue',
'Quince',
'Cucumber Ripe',
'Pear Kaiser',
'Cherry Wax Yellow',
'Avocado ripe',
'Grape White 2',
'Grapefruit White',
'Watermelon',
'Pepino',
'Onion Red Peeled',
'Apple Red Delicious',
'Salak',
'Mango Red',
'Apple Pink Lady',
'Physalis with Husk',
'Pineapple Mini',
'Pear Red',
'Nectarine Flat',
'Onion Red',
'Tamarillo',
'Peach',
'Tomato Yellow',
'Potato Sweet',
'Banana Red',
'Beetroot',
'Apple Red 2',
'Nut Pecan',
'Cauliflower',
'Apple Golden 1',
'Onion White',
'Tomato 2',
'Physalis',
'Grape White 4',
'Nut Forest',
'Redcurrant',
'Apple Red Yellow 1',
'Dates',
'Cocos',
'Tomato 3',
'Apple Granny Smith',
'Kiwi',
'Apple Red Yellow 2',
'Pear Forelle',
'Cherry 1',
'Cantaloupe 2',
'Nectarine',
'Pear Monster',
'Papaya',
'Apple Golden 2',
'Tomato not Ripened',
'Lemon',
'Pepper Orange',
'Kohlrabi',
'Potato White',
'Cherry Rainier',
'Pepper Green',
'Pear Abate',
'Huckleberry',
'Granadilla',
'Banana Lady Finger',
'Limes',
'Mangostan',
'Cucumber Ripe 2',
'Pear Williams',
'Tangelo',
'Clementine',
'Strawberry',
'Hazelnut',
'Plum',
'Pear 2',
'Guava',
'Pear',
'Kaki',
'Tomato Maroon',
'Apple Red 1',
'Eggplant',
'Strawberry Wedge',
'Tomato Cherry Red',
'Grape Pink',
'Apple Red 3',
'Pitahaya Red',
'Pepper Yellow',
'Potato Red',
'Mango',
'Melon Piel de Sapo',
'Blueberry',
'Apple Braeburn',
'Ginger Root',
'Apple Golden 3',
'Carambula',
'Chestnut',
'Lemon Meyer',
'Kumquats',
'Mulberry',
'Pepper Red',
'Tomato 4',
'Lychee',
'Corn',
'Grape White 3',
'Pomelo Sweetie',
'Cantaloupe 1',
'Banana',
'Avocado',
'Apricot',
'Peach 2',
'Pomegranate',
'Walnut',
'Tomato 1',
'Passion Fruit',
'Cherry Wax Black',
'Plum 3',
'Pear Stone',
'Orange',
'Tomato Heart',
'Rambutan'])